import { CalendarClock, CircleAlert, Plus } from "lucide-react";
import { PageHeader } from "@/components/app/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function SchedulePage() {
  return <><PageHeader eyebrow="Programação" title="Agenda e emergência" description="Resolva períodos, prioridades e overrides com timezone explícito." action={<Button><Plus /> Novo agendamento</Button>} /><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle>Próximos eventos</CardTitle><CardDescription>Ordem final considera prioridade e horário de Brasília.</CardDescription></CardHeader><CardContent className="space-y-3">{[{ date: "21 JUL", title: "Campanha Julho", target: "Canal · Lojas SP", time: "08:00 — 22:00", priority: 10 }, { date: "22 JUL", title: "Comunicado interno", target: "Dispositivo · Refeitório", time: "11:30 — 14:00", priority: 20 }, { date: "01 AGO", title: "Institucional", target: "Canal · Recepção", time: "00:00 — contínuo", priority: 5 }].map((event) => <div key={event.title} className="flex items-center gap-4 rounded-xl border p-4"><span className="grid size-12 place-items-center rounded-lg bg-primary/10 text-center font-mono text-[11px] font-semibold text-primary">{event.date}</span><div className="min-w-0 flex-1"><p className="font-medium">{event.title}</p><p className="truncate text-xs text-muted-foreground">{event.target} · {event.time}</p></div><Badge variant="secondary">P{event.priority}</Badge></div>)}</CardContent></Card><Card className="border-amber-500/20"><CardHeader><div className="flex items-center gap-2"><CircleAlert className="size-5 text-amber-400" /><CardTitle>Conteúdo emergencial</CardTitle></div><CardDescription>Override máximo, com expiração obrigatória e auditoria.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed p-6 text-center"><CalendarClock className="mx-auto mb-3 size-8 text-muted-foreground" /><p className="text-sm font-medium">Nenhum override ativo</p><p className="mt-1 text-xs text-muted-foreground">Programação normal está sendo exibida.</p><Button variant="outline" className="mt-4">Criar emergência</Button></div></CardContent></Card></div></>;
}
