import { Activity, ArrowUpRight, Clock3, Monitor, Radio, TriangleAlert } from "lucide-react";
import { PageHeader } from "@/components/app/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

const stats = [{ label: "Telas online", value: "18", note: "de 21 ativas", icon: Monitor }, { label: "Canais publicados", value: "7", note: "2 atualizados hoje", icon: Radio }, { label: "Conteúdos", value: "146", note: "12 em rascunho", icon: Activity }, { label: "Disponibilidade", value: "99,8%", note: "últimos 30 dias", icon: ArrowUpRight }];

export default function DashboardPage() {
  return <><PageHeader eyebrow="Painel operacional" title="Bom dia, administrador" description="Saúde da rede, publicações recentes e itens que precisam de atenção." /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <Card key={stat.label}><CardHeader className="flex-row items-start justify-between space-y-0"><div><CardDescription>{stat.label}</CardDescription><CardTitle className="mt-2 text-3xl font-semibold">{stat.value}</CardTitle></div><span className="rounded-lg bg-primary/10 p-2 text-primary"><stat.icon className="size-4" /></span></CardHeader><CardContent className="text-xs text-muted-foreground">{stat.note}</CardContent></Card>)}</section><section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Card><CardHeader><CardTitle>Atividade recente</CardTitle><CardDescription>Eventos administrativos auditados.</CardDescription></CardHeader><CardContent className="space-y-5">{[{ title: "Canal Recepção publicado", detail: "v24 · Ana Martins", time: "há 8 min", ok: true }, { title: "Dispositivo Loja 03 ficou offline", detail: "Último contato às 09:42", time: "há 23 min", ok: false }, { title: "Playlist Campanha Julho atualizada", detail: "4 itens alterados · Bruno Lima", time: "há 1 h", ok: true }].map((event) => <div key={event.title} className="flex gap-3"><span className={`mt-1 size-2 rounded-full ${event.ok ? "bg-primary" : "bg-amber-400"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{event.detail}</p></div><time className="text-xs text-muted-foreground">{event.time}</time></div>)}</CardContent></Card><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Saúde da rede</CardTitle><Badge variant="outline">Atualizado agora</Badge></div><CardDescription>Heartbeat padrão a cada 5 minutos.</CardDescription></CardHeader><CardContent className="space-y-5"><div><div className="mb-2 flex justify-between text-sm"><span>Dispositivos online</span><span className="font-mono">86%</span></div><Progress value={86} /></div><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border p-3"><Clock3 className="mb-2 size-4 text-primary" /><p className="text-xl font-semibold">4m 12s</p><p className="text-xs text-muted-foreground">Último heartbeat</p></div><div className="rounded-lg border p-3"><TriangleAlert className="mb-2 size-4 text-amber-400" /><p className="text-xl font-semibold">3</p><p className="text-xs text-muted-foreground">Telas offline</p></div></div></CardContent></Card></section></>;
}
